[providers]
  [providers.docker]
    exposedByDefault = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "aislxflamesop@gmail.com"
  storage = "letsencrypt/acme.json"

  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[api]
  dashboard = true

